# syntax=docker/dockerfile:1

FROM odyseeteam/transcoder-gensprite:latest AS spritegen
FROM odyseeteam/transcoder-ffmpeg:latest AS ffmpeg
FROM alpine:3.16

EXPOSE 8080

RUN apk add --no-cache libc6-compat
COPY --from=ffmpeg /build/ffmpeg /build/ffprobe /usr/local/bin/
COPY --from=spritegen /usr/src/app /usr/src/spritegen

WORKDIR /app

COPY ./dist/linux_amd64/transcoder .
# COPY ./transcoder.ex.yml ./transcoder.yml

CMD ["./transcoder", "worker"]
