FROM golang:1.16
EXPOSE 8080 2112

RUN apt-get update && apt-get install -y locales xz-utils && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

RUN curl -O https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz \
    && curl -O https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz.md5 \
    && md5sum -c ffmpeg-git-amd64-static.tar.xz.md5 \
    && tar -xf ffmpeg-git-amd64-static.tar.xz \
    && cd ffmpeg-*-static \
    && mv ffmpeg ffprobe /usr/local/bin/
ENV LANG en_US.utf8


WORKDIR /go/src/app

COPY go.mod go.mod
COPY go.sum go.sum
RUN go get -d -v ./...
RUN go install -v ./...

COPY . .

CMD [ "go", "test" "-covermode=count", "-coverprofile=coverage.out" "./..." ]
