# syntax=docker/dockerfile:1

FROM alpine:3.15 AS gather

WORKDIR /build

ADD https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz ./
RUN tar -xf ffmpeg-git-amd64-static.tar.xz && mv ffmpeg-*-static/ffmpeg ffmpeg-*-static/ffprobe ./

RUN chmod a+x ffmpeg ffprobe

FROM alpine:3.15 AS build

RUN apk add --no-cache libc6-compat
COPY --from=gather /build/ffmpeg /build/ffprobe /usr/local/bin/

WORKDIR /app

COPY ./dist/linux_amd64/worker .
# COPY ./transcoder.ex.yml ./transcoder.yml

CMD ["./worker", "start", "--work-dir", "/data"]
