# syntax=docker/dockerfile:1

# FROM odyseeteam/transcoder-gensprite:latest AS spritegen

FROM alpine:3.15 AS gather

WORKDIR /build

ADD https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-arm64-static.tar.xz ./
RUN tar -xf ffmpeg-git-arm64-static.tar.xz && mv ffmpeg-*-static/ffmpeg ffmpeg-*-static/ffprobe ./

RUN chmod a+x ffmpeg ffprobe

FROM alpine:3.15 AS build

EXPOSE 8080

RUN apk add --no-cache libc6-compat
COPY --from=gather /build/ffmpeg /build/ffprobe /usr/local/bin/
# COPY --from=spritegen /usr/src/app /usr/src/spritegen

WORKDIR /app

COPY ./dist/linux_arm64/tccli .
COPY ./conductor.ex.yml ./conductor.yml

# ENTRYPOINT ["./tccli"]
