# syntax=docker/dockerfile:1
FROM golang:1.16.10-alpine3.14 AS build

RUN apk add --no-cache git gcc musl-dev protobuf-dev make

WORKDIR /usr/src/transcoder
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

RUN make tower

FROM alpine:3.14
EXPOSE 8080

RUN apk add --no-cache libc6-compat sqlite

WORKDIR /app
COPY --from=build /usr/src/transcoder/dist/linux_amd64/tower .

CMD ["./tower", "serve"]
