openapi: "3.0.0"
info:
  title: Video Transcoder
  version: "0.0.1"

paths:
  /api/v1/tasks/{sd_hash}:
    post:
      summary: Create a transcoding task
      responses:
        "200":
          description: transcoding task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TranscodingTask"
        "400":
          description: parameter error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TranscodingTask"
    get:
      summary: Get transcoding task details
      responses:
        "200":
          description: transcoding task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TranscodingTask"
        "404":
          description: transcoding task for this SD hash does not exist
    parameters:
      - name: sd_hash
        in: path
        required: true
        schema:
          type: string
          format: byte
          maxLength: 97
  /api/v1/resources/pubkey.pem:
    get:
      summary: Retrieve a public key for this transcoder
      responses:
        "200":
          description: returns a public key in a PEM format
          content:
            application/x-pem-file: {}

components:
  schemas:
    URL:
      description: LBRY content URL
      type: string
      pattern: ^lbry://.+
    TranscodingTask:
      type: object
      required:
        - claim_id
        - signed_channel_address
      properties:
        url:
          $ref: "#/components/schemas/URL"
        claim_id:
          type: string
          format: byte
          maxLength: 41
        signed_channel_address:
          type: string
          format: byte
          description: |
            Signed channel address should be a channel address signed by channel's key owner.
            Transcoder will validate this signature against channel's public key to prevent unauthorized requests.
        encoding_parameters:
          nullable: true
          type: object
          properties:
            resolution:
              type: array
              enum:
                - 1080p
                - 720p
                - 360p
        created:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - waiting
            - abandoned
            - encoding
            - done
        progress:
          type: integer
          minimum: 0
          maximum: 100
