# syntax=docker/dockerfile:1

FROM odyseeteam/transcoder-ffmpeg:7.0 AS ffmpeg
FROM odyseeteam/transcoder-gensprite:22.10.0 AS spritegen
FROM odyseeteam/transcoder-gensprite:22.10.0

EXPOSE 8080

RUN apk add --no-cache libc6-compat
COPY --from=ffmpeg /build/ffmpeg /build/ffprobe /usr/local/bin/
COPY --from=spritegen /usr/src/app /usr/src/spritegen

WORKDIR /app

COPY ./dist/linux_amd64/transcoder .

CMD ["./transcoder", "worker"]
