// Code generated by sqlc. DO NOT EDIT.

package queue

import (
	"database/sql"
	"time"
)

type Task struct {
	ID            int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Ref           string
	Status        string
	Attempts      sql.NullInt32
	Stage         sql.NullString
	StageProgress sql.NullInt32
	Error         sql.NullString
	Worker        string
	URL           string
	SDHash        string
	Result        sql.NullString
}
